branches: 
    - main
    - +([0-9])?(.{+([0-9]),x}).x
    - {name: alpha, prerelease: true}
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/github"
    -
      - "@semantic-release/exec"
        # available - https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/plugin.md#verifyrelease
      - verifyReleaseCmd: |
          v=${nextRelease.version} && rel='false' && [[ -z $v ]] || rel='true'
          echo "releasable=$rel" | tee -a $GITHUB_OUTPUT
          echo "next-version=$v" | tee -a $GITHUB_OUTPUT
