---
name: Upload coverage to Codecov
description: Uploads coverage to Codecov

inputs:
  token:
    description: Codecov token
    required: true

runs:
  using: composite
  steps:
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4.0.1
      with:
        slug: ${{ github.repository }}
        token: ${{ inputs.token }}
        verbose: true
